[servers]
worker-node-1 ansible_host=172.20.0.11
worker-node-2 ansible_host=172.20.0.12

worker-node-1 ansible_user=ansible_user
worker-node-2 ansible_user=ansible_user

[all:vars]
ansible_ssh_private_key_file=/home/ubuntu/Documents/test/ansible/node_setup/id_rsa.pub
ansible_python_interpreter=/usr/bin/python3
ansible_host_key_checking=false # Avoides the Public Private key handshake 
