- name: Show Secrets
  hosts: worker-node-1
  become: true

  vars_files:
    - secrets.yml

  tasks:
    - name: Show Password
      ansible.builtin.debug:
        msg: "My password is {{ password }}" # password var name in the secrets.yml file
      no_log: true # Will not print anything, recommended when dealing with credentials

    - name: Show API Key
      ansible.builtin.debug:
        msg: "My API key is {{ api_key }}"
